### ISSUE TITLE
Installer doesn't copy required files to a safe location

### ISSUE THREAD

**Issue by mikeloeven** [vm-devr/aot#1]
The install.bat file should copy the required files to a unique install folder within program files or some other safe location instead of simply mapping firefox to the current location of AOT.exe I am sure I am not the only one who installed the addon from their desktop and than was confused as to why the addon stopped working when i deleted the files after running the installer.

**Comment by vm-devr** [comment]
Hello!
I'm afraid it will make things even more difficult, right now I've simplified the installation and should go smoothly now

Best regards
Vasyl Maherka
