### ISSUE TITLE
index.html keeps popping up on every click

### ISSUE THREAD

**Issue by AndyK70** [vm-devr/aot#2]
Using Firefox 60.0b6 64bit and AoT 4.4

Had AoT already installed with Firefox 57, today got the index.html to see first time. Assuming it's due to an AoT update, well 

- downloaded aot_app_4_4.zip as linked in the html.
- installed AoT with install.bat
- restarted Firefox
- click on AoT button (that pin) and html pops up again, again and again on every click
- closed Firefox
- uninstalled with according uninstall.bat
- installed again with install.bat
- started Firefox
- clicked on AoT button still html pops up on every click.

**Comment by vm-devr** [comment]
Hello!
You might forgot to unpack the archive, could you please try now? I've simplified the installation
Best regards
Vasyl Maherka
