### ISSUE TITLE
AOT.exe source code

### ISSUE THREAD

**Issue by Goutye** [vm-devr/aot#3]
Hello,
I checked the repository, however there is no source code to see if there is anything that can harm my computer.
While I love the plugin, I can't download closed eyes a .exe file without knowing its content except if it has been recognized as secured.

Is there any problem with publishing the source code of AOT here?

**Comment by vm-devr** [comment]
Hello!
Sorry, I'm new to the github, I'll try and do it
Best regards
Vasyl Maherka

**Comment by Erlite** [comment]
So.... why didn't you do it? It takes 10 seconds to send the source code. If you know how to add releases to a repo and some config/html files, adding simple source code from a "file so small it can't be harmful" shouldn't be hard.

Sounds dodgy to me.
